# This is a basic workflow to help you get started with Actions

name: Run Python Selenium headless script to raise a resume in the list on hh.ru

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "0 0 * * *"
    - cron: "5 4 * * *"
    - cron: "10 8 * * *"
    - cron: "15 12 * * *"
    - cron: "20 16 * * *"
    - cron: "25 20 * * *"
    - cron: "0 */4 * * *"
    - cron: "45 14 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install Python
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x #install the python needed

      - name: execute py script # run the run.py to get the latest data
        run: |
          pip install --upgrade pip
          pip install selenium

      - name: Raise the resume
        run: python ./bot/raise.py
        env:
          LOGIN: ${{ secrets.LOGIN }}
          KEY: ${{ secrets.KEY }} # if run.py requires passwords..etc, set it as secrets
